# версия докера.
version: '3'

# сервисы, они же образы (image), которые необходимы для работы проекта.
# ports - порты на которых будет работать/слушать сервис.
# $ docker exec -it project-name bash - подключиться непосредственно к контейнеру, дабы юзать его сервисы, например для настройки локального volums.
# volums - локальная настройка для какого-нибудь сервиса в нутри конкретного контейнера. В случает nginx - указывает ему отрабатывать по заданному 
# мною роуту в этом проекте, а не в своём дефолтном на линуксе. А в случае sql - хранит БД локально и не дропает её при уничтожении контейнера.

# таким образом, в данном примере я могу отобразить свой index.html файл.
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/                          # как бы директория с проектом на которую указывает роут из кастомного конфига.
      - ./nginx/conf.d/:/etc/nginx/conf.d/    # перенаправление nginx на мой кастомный конфиг с роутом.
    ports:
      - 8876:80
    container_name: demo-docker
  
