# версия докера.
version: '3'

# сервисы, они же образы (image), которые необходимы для работы проекта.
# ports - порты на которых будет работать/слушать сервис.
services:
  nginx:
    image: nginx:latest
    ports:
      - 8876:80
  
